[package]
name = "button-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.7.2", features = ["full"] }
eyre = "0.6.12"
futures-util = "0.3.31"
tokio = { version = "1.41.1", features = ["full"] }
